---
title: "Insolation"
author: "JCH"
date: "2022-12-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(palinsol)

## compare the obliquity over the last 2 Myr with the three solutions
times <- seq(-2e6,0,1e3)
Obl <- function(t) {c(time=t,ber78=ber78(t)['eps'],
       ber90=ber90(t)['eps'], la04=la04(t)['eps'])}

Obls <- data.frame(t(sapply(times,Obl)))

## may take about 10 seconds to run
with(Obls, {
  plot(times/1e3, ber78.eps, type='l', xlab='time (kyr)', ylab='Obliquity (radians)')
  lines(times/1e3, ber90.eps, type='l', col='red')
  lines(times/1e3, la04.eps, type='l', col='green')
  })

legend('topright', c('ber78','ber90','la04'), col=c('black','red','green'), lty=1)


## same but with a zoom over the last 300 000 years:
T <- which (times > -3e5)
with(Obls, {
  plot(times[T]/1e3, ber78.eps[T], type='l', xlab='time (kyr)', ylab='Obliquity (radians)')
  lines(times[T]/1e3, ber90.eps[T], type='l', col='red')
  lines(times[T]/1e3, la04.eps[T], type='l', col='green')
  })

legend('topright', c('ber78','ber90','la04'), col=c('black','red','green'), lty=1)


```



```{r}

## package compute Incoming Solar Radiation (insolation) for paleoclimate studies
## Features three solutions: BER78, BER90 and LA04
## Computes daily-mean, season-averaged and annual means for all latitudes
library(palinsol)

## make a little wrapper, with all default values
insolation <- function(times, astrosol=ber78,...)

sapply(times, function(tt) Insol(orbit=astrosol(tt)))

tts <- seq(from = -12e3, to = 0, by = 1e2)
isl <- insolation(tts, ber78)
plot(tts, isl, typ='l')

tts2 <- seq(from = -12e3, to = 0, by = 1e2)
isl2 <- insolation(tts2, ber90)
plot(tts2, isl2, typ='l')

tts3 <- seq(from = -12e3, to = 0, by = 1e2)
isl3 <- insolation(tts3, la04)
plot(tts3, isl3, typ='l')

```





```{r}
## Computes the distribution in lat. and long. of incoming solar radiation,
## known as a Milankovitch graph, with possibility of plotting with a
## dedicated plot function
library(palinsol)

orbit <- c(eps=0.409214, ecc=0.01672393, varpi=4.92251)

M <- Milankovitch(orbit)

plot(M, plot=contour)
plot(M, plot=contour, month=FALSE)

```








