---
title: "PaleoFire_data"
author: "JCH"
date: "2022-12-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE}
#install.packages("paleofire",repo="http://cran.r-project.org")
library(paleofire)
### select charcoal series btw: 30째-60째 lat, -110째 to -40째 long.
### have at least 1 geochronological (14C or 210Pb dating, etc)
### control point each 2500 year.
ID <- pfSiteSel(lat>30 & lat<60, long>-100 & long<(-40), date_int<=2500, num_version<400)
length(ID$id_site)
sumID <- summary(ID)

### select sites with more tna 20 samples
ID1 <- pfSiteSel(id_site %in% ID$id_site & num_samp>=20)
length(ID1$id_site)
sumID20 <- summary(ID1)

### generate map of vegetation types (rf99 classification scheme) with
### dots added to represent sample site locations
obj <- potveg(ID1, classif="rf99")
plot(obj, points=FALSE)


### transform data using function
TR1 <- pfTransform(ID1, method=c("MinMax","Box-Cox","Z-Score"))

### Method 1
### Data-binning procedure used to calculate a composite curve.
### Binning sequence must be supplied for 'pfComposite' function to calculate
### 'mean' charcoal value per series within each binning interval
### Mean is then calculated for all series
### Below 500 yr bin width is used for span of 11,000 yrs
### CI for 'pfComposite' function calculated by bootstrap re-sampling of
### binned charcoal series and calculation of the mean for each bin n times,
### using the argument 'nboot' (by default => nboot=1000).
COMP1 <- pfComposite(TR1, binning=TRUE, bins=seq(from=0,to=12000, by=500))
write.csv(COMP1$Result, file="TR1comp1a.csv")
plot(COMP1, conf=c(0.025,0.050,0.950,0.975))

### Kruskal-Wallis ANOVA on binned data issued from a "pfComposite" object
### Test difference in biomass burning activity btw different t-periods.
comparison1=pfKruskal(COMP1, p.adj="none", alpha=0.05)
plot(comparison1, conf=c(0.025,0.050,0.950,0.975))

### Moving Block Bootstrap (MBB) analysis:
### splitting charcoal series into (n-b+1) overlapping blocks of data
### (n = sample size, b = block size). Blocks are randomly selected
### (with replacement) to reconstruct new individual charcoal series
### Then estimate CIs around the new charcoal series composite mean.
### Procedure used to test significance of local minima or max. within t-series
### Note: b=NULL argument indicates that the block size is automatically
### calculated for each series using the formulation above.
circboot1 <- pfCircular(COMP1, b=NULL, nboot=1000, conf=c(0.005,0.025,0.050, 0.950, 0.975,0.995))
plot(circboot1)

```


```{r}
### Method 2 - Two-stage smoothing method:
### (i) "pre-bin" individual charcoal series using non-overlapping bins
### to ensure high sample resolution records do not create bias and
### not be interpolated for records with lower resolution
### (ii) smooth pre-binned series using a locally-weighted scatter plot
### smoother "LOWESS" with pre-defined constant bandwidth (half-width)
### given in years (hw argument)
### Note: 20 yr non-overlapping bins, LOWESS smoother 500 yr window hw of
### 1000-yr smoothing window.
### 'tarAge' => defines center of each bin (binhw being the pre-binning
### bin half width) and ages for LOWESS estim. takes place (i.e. -50 to 12,000)
### 'pfCompositeLF' function ==> CIs calculated by bootstrap re-sampling
### the pre-binned series (as opposed to individual samples) and then applying
### LOWESS curve fitting. Repeated n times using 'nboot'
### CIs estimated based on the distrib. of bootstrap replicates.
COMP2 <- pfCompositeLF(TR1, tarAge=seq(-50,12000,20), binhw=10, hw=500, nboot=1000)
write.csv(COMP2$Result, file="TR1comp2.csv")
plot(COMP2, conf=c(0.025,0.050,0.950,0.975))

### Moving Block Bootstrap (MBB) analysis:
### splitting charcoal series into (n-b+1) overlapping blocks of data
### (n = sample size, b = block size). Blocks are randomly selected
### (with replacement) to reconstruct new individual charcoal series
### Then estimate CIs around the new charcoal series composite mean.
### Procedure used to test significance of local minima or max. within t-series
### Note: b=NULL argument indicates that the block size is automatically
### calculated for each series using the formulation above.

circboot2 <- pfCircular(COMP2, b=NULL, nboot=1000, conf=c(0.005,0.025,0.050, 0.950, 0.975,0.995))
plot(circboot2)

```




```{r}
### Extract data from sites to look at frequencies across time series
fd <- pfExtract(ID1)
sumfd <- summary(fd)
sumfd

### see first six rows of data
head(fd)

### create new data.frame 'df' with select columns from 'fd' data.frame
df <- fd[,c(1,3,4)]
sum.df <- summary(df)
head(df)
tail(df)
head(sum.df)
dim(df)

### find range (min. and max.) of values to determine bins  
range(df$EST_AGE)

### now set edges of bins (i.e. sizes = 1000 year width)
edges <- c(-100-0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000, 13000, 14000)
edges1 <- c(0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000, 13000, 14000)
bin <- cut(df$EST_AGE, edges)
bin1 <- cut(df$EST_AGE, edges1)
sum.bin <- summary(bin)
sum.bin1 <- summary(bin1)
sum.bin
sum.bin1
sum(sum.bin)
sum(sum.bin1)

### use a pie chart to show sample sizes per bin (1000 years)
bins <- c(1859, 1404, 1008, 919, 775, 864, 879, 823, 428, 249, 188, 117, 90, 15)

pie(bins, col = c("lightblue", "red3","white", "tan", "blue", "yellow", "gray75",  "cyan3", "green4", "orange4", "pink", "red1", "gray25", "orange2"), labels = " ")

pie(bins, col = rainbow(14), labels = " ")

```


```{r}
### Plot the first site raw charcoal data
### use logic operator "==" to extract only first site data
### x = time ("est_age" = column 3 in "fd" dframe)
### y = charcoal "quantity" (column 4 of "fd" dframe)
### for only the first site in "ID1" dframe

plot(fd[fd[,1]==ID1$id_site[1],3], fd[fd[,1]==ID1$id_site[1],4], type="l", main=ID1$site_name[1], xlab="Age", ylab="raw Char")

### Scatter plot the first site raw charcoal data
plot(x=fd$EST_AGE, y=log(fd$QUANTITY), xlim=c(0,11000), xlab="Age", ylab="raw Char")

plot(x=df[,2], y=log(df[,3]), xlim=c(0,14000), xlab="Age", ylab="raw Char")

```


```{r}
### Scatter plot the first site raw charcoal data
plot(x=fd[fd[,1]==ID1$id_site[57],3], y=fd[fd[,1]==ID1$id_site[57],4])
sum(fd[fd[,1]==ID1$id_site[57],4])

sum.site57char <- summary(fd[fd[,1]==ID1$id_site[57],4])
sum.site57ages <- summary(fd[fd[,1]==ID1$id_site[57],3])

sum.site57char
sum.site57ages

```



```{r}
### Temperate Grassland ===> rf99 = 11
### Mixed Grass Prairie ===> rf99 = 10
### Savanna ===> rf99 = 9
### Mixed Forest ===> rf99 = 8
### Boreal Deciduous Forest/Woodland ===> rf99 = 7
### Boreal Evergreen Forest/Woodland ===> rf99 = 6
### Temperate Deciduous Forest/Woodland ===> rf99 = 5

### North American Savana, rf99==9 (Ramankutty and Foley 1999)
NA9 <- pfSiteSel(rf99==9, continent=="North America")
plot(NA9, zoom="world")
length(NA9$id_site)
sumNA9 <- summary(NA9)

### North American Temperate Grasslands (rf99==11)
NA11 <- pfSiteSel(rf99==11, continent=="North America")
plot(NA11, zoom="world")
length(NA11$id_site)
sumNA11 <- summary(NA11)

### Diagnostic function: prints 1 page per site of charcoal freq.
pfDiagnostic(ID1, method=c("MinMax","Box-Cox","Z-Score"))
```

